use crate::config::{AppConfig, BackupConfig, ServiceBackupConfig, StdinDump};
use crate::hostexec::HostExec;
use crate::services::{valid_rel_path, Service};
use anyhow::Result;
use serde::Serialize;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

pub const PASSWORD_FILE: &str = ".restic_password";
pub const INITED_FILE: &str = ".restic_inited";
pub const SCRIPT_FILE: &str = "backup.sh";

/// Repository URL for a service: base + name, or custom template.
pub fn repository_for(cfg: &BackupConfig, service: &str) -> String {
    if let Some(tpl) = &cfg.repository_template {
        tpl.replace("{base}", &cfg.repository_base)
            .replace("{service}", service)
    } else {
        format!("{}{}", cfg.repository_base, service)
    }
}

/// Timer/service unit names for a service backup.
pub fn unit_names(cfg: &BackupConfig, service: &str) -> (String, String) {
    (
        format!("{}-{}.service", cfg.unit_prefix, service),
        format!("{}-{}.timer", cfg.unit_prefix, service),
    )
}

// ---------------------------------------------------------------------------
// backup.sh rendering
// ---------------------------------------------------------------------------

/// Render the per-service backup script (TechOverflow style, generalized).
/// All paths are HOST paths.
pub fn render_backup_script(
    cfg: &AppConfig,
    svc: &Service,
    bcfg: &ServiceBackupConfig,
) -> Result<String> {
    let repo = repository_for(&cfg.backup, &svc.name);
    let dir = svc.host_dir.to_string_lossy();
    let compose_file = svc
        .compose_path
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "docker-compose.yml".into());
    let restic = if cfg.backup.restic_binary == "auto" {
        "restic".to_string()
    } else {
        shell_quote(&cfg.backup.restic_binary)
    };
    // compose binary: either pinned, or auto-detected at script runtime
    let compose_bin = if cfg.systemd.compose_binary == "auto" {
        "$COMPOSE_BIN".to_string()
    } else {
        shell_quote(&cfg.systemd.compose_binary)
    };

    let mut s = String::new();
    s.push_str("#!/bin/bash\n# generated by ddm — do not edit by hand\n");
    s.push_str("set -euo pipefail\n");
    s.push_str(&format!("export NAME={}\n", shell_quote(&svc.name)));
    s.push_str(&format!(
        "export RESTIC_REPOSITORY={}\n",
        shell_quote(&repo)
    ));
    s.push_str(&format!(
        "export RESTIC_PASSWORD_FILE={}\n",
        shell_quote(&format!("{dir}/{PASSWORD_FILE}"))
    ));
    for (k, v) in &cfg.backup.extra_env {
        s.push_str(&format!("export {k}={}\n", shell_quote(v)));
    }
    s.push_str(&format!("cd {}\n\n", shell_quote(&dir)));
    if cfg.systemd.compose_binary == "auto" {
        s.push_str(
            "if command -v docker-compose >/dev/null 2>&1; then COMPOSE_BIN='docker-compose'; else COMPOSE_BIN='docker compose'; fi\n\n",
        );
    }

    s.push_str(&format!(
        "if [ ! -f \"{INITED_FILE}\" ]; then\n  {restic} init\n  touch {INITED_FILE}\nfi\n\n"
    ));

    // stdin dumps (pg_dump-style)
    for dump in &bcfg.stdin_dumps {
        let mut cmd_parts: Vec<String> = vec![
            format!("{compose_bin} -f {}", shell_quote(&compose_file)),
            "exec".into(),
            "-T".into(),
            dump.service.clone(),
        ];
        cmd_parts.extend(dump.command.iter().cloned());
        let cmdline = cmd_parts.join(" ");
        if let Some(envf) = &dump.env_file {
            s.push_str(&format!("set -a; source {}; set +a\n", shell_quote(envf)));
        }
        // ${VAR} stays literal and expands at runtime from the sourced env file
        s.push_str(&format!(
            "{cmdline} | {restic} --verbose backup --stdin --stdin-filename={}\n\n",
            shell_quote(&dump.filename.replace("{service}", &svc.name))
        ));
    }

    // file backup
    let mut paths: Vec<String> = bcfg.paths.clone();
    if paths.is_empty() {
        paths = vec![compose_file, SCRIPT_FILE.to_string()];
    }
    for p in &paths {
        if !valid_rel_path(p) {
            anyhow::bail!("invalid backup path '{p}'");
        }
    }
    let mut excl: Vec<String> = cfg.backup.excludes.clone();
    excl.extend(bcfg.excludes.clone());
    // never back up the password into the repo
    excl.push(PASSWORD_FILE.to_string());
    let mut cmd = format!("{restic} --verbose backup");
    for p in &paths {
        cmd.push_str(&format!(" {}", shell_quote(p)));
    }
    for e in &excl {
        cmd.push_str(&format!(" --exclude {}", shell_quote(e)));
    }
    s.push_str(&cmd);
    s.push('\n');

    if let Some(r) = &cfg.backup.retention {
        let mut f = format!("\n{restic} forget --prune");
        if let Some(k) = r.keep_last {
            f.push_str(&format!(" --keep-last {k}"));
        }
        if let Some(k) = r.keep_daily {
            f.push_str(&format!(" --keep-daily {k}"));
        }
        if let Some(k) = r.keep_weekly {
            f.push_str(&format!(" --keep-weekly {k}"));
        }
        if let Some(k) = r.keep_monthly {
            f.push_str(&format!(" --keep-monthly {k}"));
        }
        s.push_str(&f);
        s.push('\n');
    }
    Ok(s)
}

pub fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

// ---------------------------------------------------------------------------
// Timer units
// ---------------------------------------------------------------------------

pub fn render_backup_units(cfg: &AppConfig, svc: &Service) -> (String, String) {
    let (svc_unit, timer_unit) = unit_names(&cfg.backup, &svc.name);
    let script = svc.host_dir.join(SCRIPT_FILE);
    let service_unit = format!(
        "[Unit]\nDescription=Backup for {name} (ddm)\nRequires=docker.service\nAfter=docker.service\n\n[Service]\nType=oneshot\nWorkingDirectory={dir}\nExecStart={script}\n",
        name = svc.name,
        dir = svc.host_dir.to_string_lossy(),
        script = script.to_string_lossy(),
    );
    let timer_unit_content = format!(
        "[Unit]\nDescription=Backup timer for {name} (ddm)\n\n[Timer]\nOnCalendar={cal}\nPersistent=true\n\n[Install]\nWantedBy=timers.target\n",
        name = svc.name,
        cal = cfg.backup.on_calendar,
    );
    let _ = svc_unit;
    let _ = timer_unit;
    (service_unit, timer_unit_content)
}

// ---------------------------------------------------------------------------
// Provision & check
// ---------------------------------------------------------------------------

/// Generate a random password file (0600). Returns whether it was created.
pub fn ensure_password_file(svc: &Service) -> Result<bool> {
    use std::os::unix::fs::PermissionsExt;
    let p = svc.dir.join(PASSWORD_FILE);
    if p.exists() {
        return Ok(false);
    }
    let pw = crate::users::generate_password();
    std::fs::write(&p, pw)?;
    std::fs::set_permissions(&p, std::fs::Permissions::from_mode(0o600))?;
    Ok(true)
}

/// Write script + units + init repo + enable timer. Idempotent.
pub async fn provision(
    cfg: &AppConfig,
    host: &Arc<dyn HostExec>,
    svc: &Service,
    host_bin: &str,
) -> Result<Vec<String>> {
    let mut done = vec![];
    let bcfg = svc.meta.backup.clone().unwrap_or_default();

    if ensure_password_file(svc)? {
        done.push("created .restic_password".into());
    }
    let script = render_backup_script(cfg, svc, &bcfg)?;
    crate::services::write_service_file(&svc.dir, SCRIPT_FILE, &script, 0o755)?;
    done.push("wrote backup.sh".into());

    if bcfg.schedule_enabled {
        let (su, tu) = render_backup_units(cfg, svc);
        let (sname, tname) = unit_names(&cfg.backup, &svc.name);
        let sdir = Path::new(&cfg.paths.host_systemd_dir);
        std::fs::write(sdir.join(&sname), su)?;
        std::fs::write(sdir.join(&tname), tu)?;
        done.push(format!("wrote {sname} + {tname}"));
        host.run("systemctl", &["daemon-reload".into()]).await?;
        let en = host
            .run("systemctl", &["enable".into(), "--now".into(), tname])
            .await?;
        done.push(format!("enable --now timer: status {}", en.status));
    }

    // restic init on the host (idempotent; .restic_inited marker on host dir)
    let inited_marker = svc.dir.join(INITED_FILE);
    if !inited_marker.exists() {
        let repo = repository_for(&cfg.backup, &svc.name);
        let script = format!(
            "cd {dir} && RESTIC_REPOSITORY={repo} RESTIC_PASSWORD_FILE={pw} {bin} init && touch {marker}",
            dir = shell_quote(&svc.host_dir.to_string_lossy()),
            repo = shell_quote(&repo),
            pw = shell_quote(&svc.host_dir.join(PASSWORD_FILE).to_string_lossy()),
            bin = shell_quote(host_bin),
            marker = INITED_FILE,
        );
        let out = host.run("bash", &["-c".into(), script]).await?;
        done.push(format!("restic init exit {}", out.status));
    }
    Ok(done)
}

// ---------------------------------------------------------------------------
// Check report
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize)]
pub struct BackupIssue {
    pub code: String,
    pub message: String,
    pub fixable: bool,
}

#[derive(Debug, Clone, Serialize)]
pub struct BackupCheckReport {
    pub service: String,
    pub enabled: bool,
    pub password_file: bool,
    pub script: bool,
    pub repo_inited: bool,
    pub timer_exists: bool,
    pub timer_enabled: Option<String>,
    pub timer_active: Option<String>,
    pub last_run: Option<String>,
    pub repository: String,
    pub issues: Vec<BackupIssue>,
}

fn bissue(code: &str, msg: impl Into<String>) -> BackupIssue {
    BackupIssue {
        code: code.to_string(),
        message: msg.into(),
        fixable: true,
    }
}

pub async fn check(cfg: &AppConfig, host: &Arc<dyn HostExec>, svc: &Service) -> BackupCheckReport {
    let bcfg = svc.meta.backup.clone().unwrap_or_default();
    let mut issues = vec![];

    let password_file = svc.dir.join(PASSWORD_FILE).is_file();
    if !password_file {
        issues.push(bissue("password_missing", ".restic_password missing"));
    }
    let script = svc.dir.join(SCRIPT_FILE).is_file();
    if !script {
        issues.push(bissue("script_missing", "backup.sh missing"));
    }
    let repo_inited = svc.dir.join(INITED_FILE).is_file();
    if !repo_inited {
        issues.push(bissue("repo_not_inited", "restic repo not initialized"));
    }

    // restic present on host?
    match host.which("restic").await {
        Ok(None) => issues.push(BackupIssue {
            code: "restic_missing".into(),
            message: "restic binary not found on host".into(),
            fixable: false,
        }),
        Err(e) => issues.push(BackupIssue {
            code: "check_error".into(),
            message: format!("host exec failed: {e:#}"),
            fixable: false,
        }),
        _ => {}
    }

    let (sname, tname) = unit_names(&cfg.backup, &svc.name);
    let sdir = Path::new(&cfg.paths.host_systemd_dir);
    let timer_exists = sdir.join(&tname).is_file();
    if bcfg.schedule_enabled && !timer_exists {
        issues.push(bissue("timer_missing", "backup timer unit missing"));
    }
    let (t_enabled, t_active) = if timer_exists {
        crate::systemd::unit_state(host, &tname).await
    } else {
        (None, None)
    };
    if timer_exists {
        if !matches!(
            t_enabled.as_deref(),
            Some("enabled") | Some("enabled-runtime")
        ) {
            issues.push(bissue("timer_disabled", "timer not enabled"));
        }
        if !matches!(t_active.as_deref(), Some("active")) {
            issues.push(bissue("timer_inactive", "timer not active"));
        }
    }
    let _ = sname;

    // last_run: newest file mtime of .restic_* markers? read from
    // journalctl is heavy — use host `systemctl show -p ExecMainStatus`.
    let last_run = if timer_exists {
        host.run(
            "systemctl",
            &[
                "show".into(),
                sname.clone(),
                "-p".into(),
                "ExecMainStartTimestamp".into(),
            ],
        )
        .await
        .ok()
        .map(|o| {
            o.stdout
                .trim()
                .trim_start_matches("ExecMainStartTimestamp=")
                .to_string()
        })
        .filter(|s| !s.is_empty() && s != "n/a")
    } else {
        None
    };
    if last_run.is_none() && repo_inited {
        issues.push(bissue("never_run", "no backup run recorded"));
    }

    BackupCheckReport {
        service: svc.name.clone(),
        enabled: bcfg.enabled,
        password_file,
        script,
        repo_inited,
        timer_exists,
        timer_enabled: t_enabled,
        timer_active: t_active,
        last_run,
        repository: repository_for(&cfg.backup, &svc.name),
        issues,
    }
}

// ---------------------------------------------------------------------------
// restic query helpers
// ---------------------------------------------------------------------------

fn restic_env_script_prefix(cfg: &AppConfig, svc: &Service) -> String {
    let repo = repository_for(&cfg.backup, &svc.name);
    let mut s = format!(
        "cd {dir} && export RESTIC_REPOSITORY={repo} RESTIC_PASSWORD_FILE={pw}",
        dir = shell_quote(&svc.host_dir.to_string_lossy()),
        repo = shell_quote(&repo),
        pw = shell_quote(&svc.host_dir.join(PASSWORD_FILE).to_string_lossy()),
    );
    for (k, v) in &cfg.backup.extra_env {
        s.push_str(&format!(" {k}={}", shell_quote(v)));
    }
    s
}

/// `restic snapshots --json` for a service.
pub async fn snapshots(
    cfg: &AppConfig,
    host: &Arc<dyn HostExec>,
    svc: &Service,
    restic_bin: &str,
) -> Result<serde_json::Value> {
    let script = format!(
        "{} && {} snapshots --json",
        restic_env_script_prefix(cfg, svc),
        shell_quote(restic_bin)
    );
    let out = host.run("bash", &["-c".into(), script]).await?;
    if !out.success() {
        anyhow::bail!("restic snapshots failed: {}", out.stderr.trim());
    }
    Ok(serde_json::from_str(&out.stdout).unwrap_or(serde_json::json!([])))
}

/// Build the host script for forget --prune.
pub fn forget_script(cfg: &AppConfig, svc: &Service, restic_bin: &str) -> String {
    let mut extra = String::new();
    if let Some(r) = &cfg.backup.retention {
        if let Some(k) = r.keep_last {
            extra.push_str(&format!(" --keep-last {k}"));
        }
        if let Some(k) = r.keep_daily {
            extra.push_str(&format!(" --keep-daily {k}"));
        }
        if let Some(k) = r.keep_weekly {
            extra.push_str(&format!(" --keep-weekly {k}"));
        }
        if let Some(k) = r.keep_monthly {
            extra.push_str(&format!(" --keep-monthly {k}"));
        }
    }
    format!(
        "{} && {} forget --prune{}",
        restic_env_script_prefix(cfg, svc),
        shell_quote(restic_bin),
        extra
    )
}

/// Build the host script for `restic restore`.
pub fn restore_script(
    cfg: &AppConfig,
    svc: &Service,
    restic_bin: &str,
    snapshot: &str,
    target_dir: &str,
) -> Result<String> {
    if snapshot
        .chars()
        .any(|c| !(c.is_ascii_alphanumeric() || c == '-'))
        && snapshot != "latest"
    {
        anyhow::bail!("invalid snapshot id");
    }
    let target = PathBuf::from(target_dir);
    if !target.is_absolute() || target_dir.contains("..") {
        anyhow::bail!("target_dir must be an absolute path without '..'");
    }
    Ok(format!(
        "{} && {} restore {} --target {}",
        restic_env_script_prefix(cfg, svc),
        shell_quote(restic_bin),
        shell_quote(snapshot),
        shell_quote(target_dir)
    ))
}

/// Script to run the backup now.
pub fn run_script(svc: &Service) -> String {
    shell_quote(&svc.host_dir.join(SCRIPT_FILE).to_string_lossy()).to_string()
}

/// Expand `${VAR}` in a dump command from an env file's contents.
/// (Used for validation of meta.yaml at save time.)
#[allow(dead_code)]
pub fn expand_env_vars(cmd: &[String], env: &HashMap<String, String>) -> Vec<String> {
    cmd.iter()
        .map(|a| {
            let mut s = a.clone();
            for (k, v) in env {
                s = s.replace(&format!("${{{k}}}"), v);
            }
            s
        })
        .collect()
}

/// Validate a StdinDump list against a compose file's service names.
#[allow(dead_code)]
pub fn validate_dumps(dumps: &[StdinDump], compose_services: &[String]) -> Result<()> {
    for d in dumps {
        if d.filename.is_empty() || d.filename.contains('/') || d.filename.contains("..") {
            anyhow::bail!("invalid stdin_dump filename '{}'", d.filename);
        }
        if !compose_services.iter().any(|s| s == &d.service) {
            anyhow::bail!("stdin_dump service '{}' not in compose services", d.service);
        }
        if d.command.is_empty() {
            anyhow::bail!("stdin_dump '{}' has empty command", d.filename);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::RetentionPolicy;

    fn cfg() -> AppConfig {
        let mut c = AppConfig::default();
        c.paths.services_root = "/tmp/svc".into();
        c.paths.host_services_root = Some("/opt/services".into());
        c.backup.enabled = true;
        c.backup.repository_base = "rest:http://restic:pw@10.0.0.1:8000/".into();
        c.backup.retention = Some(RetentionPolicy {
            keep_last: Some(7),
            keep_daily: Some(7),
            keep_weekly: Some(4),
            keep_monthly: None,
        });
        c.systemd.compose_binary = "/usr/bin/docker-compose".into();
        c
    }

    fn svc(dir: &Path) -> Service {
        let compose = dir.join("docker-compose.yml");
        std::fs::write(&compose, "services:\n  db:\n    image: postgres\n").unwrap();
        Service {
            name: "pg-app".into(),
            dir: dir.to_path_buf(),
            host_dir: PathBuf::from("/opt/services/pg-app"),
            compose_path: compose,
            meta: Default::default(),
        }
    }

    #[test]
    fn repo_template() {
        let c = cfg();
        assert_eq!(
            repository_for(&c.backup, "web-1"),
            "rest:http://restic:pw@10.0.0.1:8000/web-1"
        );
        let mut c2 = c.clone();
        c2.backup.repository_template = Some("s3:bucket/{service}".into());
        assert_eq!(repository_for(&c2.backup, "x"), "s3:bucket/x");
    }

    #[test]
    fn render_script() {
        let tmp = tempfile::tempdir().unwrap();
        let s = svc(tmp.path());
        let mut bcfg = ServiceBackupConfig {
            paths: vec!["docker-compose.yml".into(), "data".into()],
            ..Default::default()
        };
        bcfg.stdin_dumps.push(StdinDump {
            filename: "pg-app.sql".into(),
            service: "db".into(),
            command: vec!["pg_dump".into(), "-U".into(), "${POSTGRES_USER}".into()],
            env_file: Some(".env".into()),
        });
        let script = render_backup_script(&cfg(), &s, &bcfg).unwrap();
        assert!(script.contains("RESTIC_REPOSITORY='rest:http://restic:pw@10.0.0.1:8000/pg-app'"));
        assert!(script.contains("cd '/opt/services/pg-app'"));
        assert!(script.contains("restic init") || script.contains("init"));
        assert!(script.contains("--stdin-filename='pg-app.sql'"));
        assert!(script.contains("--exclude '.restic_password'"));
        assert!(script.contains("--keep-last 7"));
    }

    #[test]
    fn timer_units() {
        let tmp = tempfile::tempdir().unwrap();
        let s = svc(tmp.path());
        let c = cfg();
        let (su, tu) = render_backup_units(&c, &s);
        assert!(su.contains("ExecStart=/opt/services/pg-app/backup.sh"));
        assert!(su.contains("Type=oneshot"));
        assert!(tu.contains("OnCalendar=daily"));
        assert!(tu.contains("WantedBy=timers.target"));
    }

    #[test]
    fn valid_dump_names() {
        let dumps = vec![StdinDump {
            filename: "a.sql".into(),
            service: "db".into(),
            command: vec!["pg_dump".into()],
            env_file: None,
        }];
        assert!(validate_dumps(&dumps, &["db".to_string()]).is_ok());
        let bad = vec![StdinDump {
            filename: "../x".into(),
            service: "db".into(),
            command: vec!["x".into()],
            env_file: None,
        }];
        assert!(validate_dumps(&bad, &["db".to_string()]).is_err());
    }

    #[test]
    fn restore_target_validation() {
        let tmp = tempfile::tempdir().unwrap();
        let s = svc(tmp.path());
        let c = cfg();
        assert!(restore_script(&c, &s, "restic", "latest", "/tmp/restore-1").is_ok());
        assert!(restore_script(&c, &s, "restic", "abc;rm", "/tmp/x").is_err());
        assert!(restore_script(&c, &s, "restic", "latest", "rel/path").is_err());
        assert!(restore_script(&c, &s, "restic", "latest", "/tmp/../x").is_err());
    }
}
